// client/src/components/App.tsx
import React from 'react';
import { noUser } from '../auth';
import { useAuthState } from '../hooks/useAuthState';
import { Login } from './Login';

export const App: React.FC = () => {
  const user = useAuthState(noUser, { autoLogin: false });

  return (
    <div className="container mx-auto px-6">
      {user.loggedIn ? <div>Welcome, {user.email}!</div> : <Login user={user} />}
    </div>
  );
};

// client/src/App.svelte
<script lang="ts">
  import { defaultUser, setAuthStateListener } from "./firebase";
  import type { User } from "./types";
  import Login from "./Login.svelte";

  let currentUser: User = defaultUser;
  setAuthStateListener((user) => {
    currentUser = user;
  });
</script>

{#if currentUser.loggedIn}
  <h1>Welcome, {currentUser.email}!</h1>
  <p>{currentUser.token}</p>
{:else}
  <Login />
{/if}
